# Generated by Django 5.2.7 on 2025-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
