# Generated by Django 6.1.2 on 2026-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
